### ISSUE TITLE
Passing arguments to constructors

### ISSUE THREAD

**Issue by simon-p-r** [kevinconway/Modelo.js#16]
Hi

I would like to pass an object to my constructors like this

````JS
var Console = require('./console.js');
var File = require('./file.js');
var Modelo = require('modelo');

var internals = {};

module.exports = internals.Logger = function (options) {
	//extend from transport objects

	options = options || {};
	Console.call(this, options);
    File.call(this, options);


};

Modelo.inherits(internals.Logger, Console, File);
````
Any help would be appreciated!

**Comment by kevinconway** [comment]
Arguments should pass to your constructor unmodified. Are you getting an exception while creating new instances?

**Comment by kevinconway** [comment]
I double checked that there are tests for the project which ensure options are passed through. I also stubbed out some code based on your snippet to make sure there aren't any errors.

Re-open the issue if you hit any road blocks. You should be OK, though.

**Comment by simon-p-r** [comment]
I am looking to create an object extending the properties of the other 2 objects however when calling the code it prints this.

````JS
var logger = new Logger(options);
console.log(logger instanceof Console); // prints true
console.log(logger instanceof File); // prints false

````
Basically I need to extend a base object to create a main logging class, sorry I am an extreme novice with progamming

**Comment by kevinconway** [comment]
That is correct. The `instanceof` operator only works with single inheritance. Inheritance libraries which support multiple inheritance will provide you with some other method for performing `instanceof`.

When you use `Modelo.inherits` it adds an `isInstance` method to each instance of your prototype. Ex:

``` javascript
var logger = new Logger(options);
console.log(logger.isInstance(Console)); // prints true
console.log(logger.isInstance(File)); // prints true
```

**Comment by simon-p-r** [comment]
Ok I saw this property, however when I call modelo it overwrites methods on the other object so I cannot create a object that inherits properties from both objects.

**Comment by kevinconway** [comment]
The inheritance works by copying over properties from the prototypes of each object passed into `Modelo.inherits`. Here's an example:

``` javascript
function Console(options) { }
Console.prototype.doSomething = function doSomething() { console.log('Console doing something.'); };

function File(options) {}
File.prototype.doSomething = function doSomething() { console.log('File doing something.'); };

function Logger(options) {}
Modelo.inherits(Logger, Console, File);

var logger = new Logger();
logger.doSomething(); // prints "File doing something".
```

If there is a name collision then the name will always reference the property from the last prototype (left to right order). If you need to customize this behaviour you can do something similar to the Logger constructor you showed above:

``` javascript
function Logger(options) {}
Modelo.inherits(Logger, Console, File);
Logger.prototype.doSomething = function doSomething() {
    console.log('Logger doing something.');
    File.prototype.doSomething.call(this);
    Console.prototype.doSomething.call(this);
};
```

**Comment by simon-p-r** [comment]
Thanks for the pointers, I realise I can't get round it without creating a base object and then inherit from that object separately both for my console and file modules.  I basically wanted a switch I can turned one on and the other off or alternatively use both at same time.

Appreciate your help!

**Comment by kevinconway** [comment]
It sounds like maybe you need a different abstraction. For example, in the standard library Python logger they have separate objects for the logger, itself, and the transport layers on which it publishes messages. A similar architecture may make it much easier to write messages across multiple transports without needing to inherit from different prototypes each time.

Also, you should take a look at https://github.com/winstonjs/winston. If it suits you needs you may be able to skip to the next part of your project. Alternatively, you may just get some good ideas from its code.

**Comment by simon-p-r** [comment]
Thanks for the advice!
