### ISSUE TITLE
Missing super_ property

### ISSUE THREAD

**Issue by bjornharrtell** [kevinconway/Modelo.js#17]
From the docs at https://nodejs.org/docs/latest/api/util.html#util_util_inherits_constructor_superconstructor:

"As an additional convenience, superConstructor will be accessible through the constructor.super_ property."

Seems like the super_ property isn't added when using modelo.inherits.

**Comment by kevinconway** [comment]
You are right. It isn't getting added. I meant for `modelo.inherits` to exactly match the behaviour of `utils.inherits` for single inheritance so that is a pretty big oversight. I'll push up a fix soon.

**Comment by kevinconway** [comment]
Ok, patch is up and the new build (4.2.0) is available on npm.

Thanks again for testing the lib out and reporting the bug!
